### ISSUE TITLE
Proper pomodoro-break workflow

### ISSUE THREAD

**Issue by tvooo** [edelprino/pom#6]
Hi, thanks for the work on this. As far as I can see, I can either start a pomodoro or a break, but it does not seem to automatically switch to a break after a pomodoro, and then back to a pomodoro after a break, right? Or am I missing something?

It would be nice if that could happen automatically :)

**Comment by edelprino** [comment]
Yes, you'are right. But you can configurate `~/.pom.yml` for start a break when pomodoro is finished.

```
commands:
    pomodoro:
...
        end:
            - terminal-notifier -message "Pomodoro ended!"
            - pom -b start
```
